# Generated by Django 4.1.3 on 2022-11-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'categoriaproducto', 'verbose_name_plural': 'categoriasproducto'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='contenido',
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
