# Generated by Django 4.1.3 on 2022-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondepedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
